# Generated by Django 6.0.4 on 2026-04-07 18:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('no2', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('pm2_5', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('no', models.FloatField(blank=True, null=True)),
                ('nox', models.FloatField(blank=True, null=True)),
                ('nh3', models.FloatField(blank=True, null=True)),
                ('c7h8', models.FloatField(blank=True, null=True)),
                ('c6h6', models.FloatField(blank=True, null=True)),
                ('c8h10', models.FloatField(blank=True, null=True)),
                ('as_ng_m3', models.FloatField(blank=True, null=True)),
                ('ni_ng_m3', models.FloatField(blank=True, null=True)),
                ('cd_ng_m3', models.FloatField(blank=True, null=True)),
                ('pb_ng_m3', models.FloatField(blank=True, null=True)),
                ('b_a_p_ng_m3', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('max_wind_speed', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('relative_humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('solar_radiation', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('noise', models.FloatField(blank=True, null=True)),
                ('source_created_date', models.DateField(blank=True, null=True)),
                ('source_removed_date', models.DateField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='air_quality.station')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-date', 'station__name'],
                'constraints': [models.UniqueConstraint(fields=('station', 'date'), name='unique_station_date_measurement')],
            },
        ),
    ]
