# Generated by Django 6.0.4 on 2026-04-16 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-measured_at', 'station__name'], 'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.RemoveConstraint(
            model_name='measurement',
            name='unique_station_date_measurement',
        ),
        migrations.AddField(
            model_name='measurement',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('station', 'measured_at'), name='unique_station_measured_at'),
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='source_created_date',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='source_removed_date',
        ),
    ]
